force-app/main/default/objects/Account_Plans__c/Account_Plans__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plans__c/fields/Client_IT_Landscape__c.field-meta.xml
<CustomField>
    <fullName>Client_IT_Landscape__c</fullName>
    <label>Client IT Landscape (max 1000 letters)</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AccountPlanTest1.cls
@IsTest
public class AccountPlanTest1{    
    public static List<Account> accounts = new List<Account>();                                                // This is to handle BULK Topic list
    public static list<Account_Plans__c> accountplan = new List<Account_Plans__c>();  // This is to handle BULK Topic Assgn list
    public static Id entId;
        
    public static void createTestAccount() {        
    }
    
    @IsTest
    static void UseCase1(){
        Account acc1= new Account();
        acc1.Name='Triumph Group';
        acc1.BillingState='Mumbai';
        
        // System.assertEquals(null, leads);
        
        
        system.debug('ACCOUNT--'+accounts);
        insert accounts;
        
        Account_Plans__c ap1= new Account_Plans__c();
        ap1.Name='Pranav';
        ap1.Client_IT_Landscape__c='ABC';
        
        
        system.debug('ACCOUNTPLAN--'+accountplan);
        insert accountplan;

        // Creating Class constructor
        
        accountPlanController crc = new accountPlanController();
        String recordId = String.Valueof(accountplan);
        system.debug('REC --'+recordId);

        Test.startTest();
        Test.StopTest();
        }
}