force-app/main/default/objects/Account_Plans__c/Account_Plans__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plans__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Plans__c/fields/Client_IT_Landscape__c.field-meta.xml
<CustomField>
    <fullName>Client_IT_Landscape__c</fullName>
    <label>Client IT Landscape (max 1000 letters)</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Plans__c/fields/Client_Organization_Towers__c.field-meta.xml
<CustomField>
    <fullName>Client_Organization_Towers__c</fullName>
    <label>Client Organization/Towers</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Plans__c/fields/Key_Business_Priorities_of_Client__c.field-meta.xml
<CustomField>
    <fullName>Key_Business_Priorities_of_Client__c</fullName>
    <label>Key Business Priorities of Client</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Plans__c/fields/Major_Events__c.field-meta.xml
<CustomField>
    <fullName>Major_Events__c</fullName>
    <label>Major Events</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Plans__c/fields/Our_Business_Goals_Projects_we_want_to__c.field-meta.xml
<CustomField>
    <fullName>Our_Business_Goals_Projects_we_want_to__c</fullName>
    <label>Our Business Goals &amp; Projects we want to</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Plans__c/fields/Our_Revenue_Targets__c.field-meta.xml
<CustomField>
    <fullName>Our_Revenue_Targets__c</fullName>
    <label>Our Revenue Targets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Plans__c/fields/Potential_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Potential_Revenue__c</fullName>
    <label>Company Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/accountPlanController.cls
public class accountPlanController {
	@AuraEnabled
    public static List<Account> getAccountPlanName(String recordId){
        List<Account> planName = [SELECT Id, CreatedBy.Name, LastModifiedBy.Name, Name,(SELECT Id, Account_Name__c, Name, Potential_Revenue__c, 
                                                    Client_Organization_Towers__c, Our_Revenue_Targets__c, 
                                                    Key_Business_Priorities_of_Client__c,Our_Business_Goals_Projects_we_want_to__c,                                                   
                                                    Major_Events__c, 
                                                    Client_IT_Landscape__c, CreatedBy.Name, CreatedDate, 
                                                    LastModifiedBy.Name, LastModifiedDate
                                                    FROM Account_Plans__r) FROM Account WHERE Id =: recordId];   
        return planName;
    }
    
    @AuraEnabled
    public static Account_Plans__c addAccountPlan(String recordId, String planName, Double revenue,  String organizationTowers, 
                                                  Double revenueTargets, String businessGoals, String keyBusiness, 
                                                  String events,  
                                                   String clientLandscape){
        Account_Plans__c addPlan = new Account_Plans__c();
        addPlan.Account_Name__c = recordId; 
        addPlan.Name = planName; 
        addPlan.Potential_Revenue__c = revenue;
        addPlan.Client_Organization_Towers__c = organizationTowers;
        addPlan.Our_Revenue_Targets__c = revenueTargets;
        addPlan.Our_Business_Goals_Projects_we_want_to__c = businessGoals;
        addPlan.Key_Business_Priorities_of_Client__c = keyBusiness;
        addPlan.Major_Events__c = events;
        addPlan.Client_IT_Landscape__c = clientLandscape;
        insert addPlan;
        return addPlan;
    }
        
    @AuraEnabled
    public static Account_Plans__c updateAccountPlan(String recordId, String planName, Double revenue,  String organizationTowers, 
                                                  Double revenueTargets, String businessGoals, String keyBusiness, 
                                                  String events,  
                                                   String clientLandscape){
        Account_Plans__c updatePlan = [SELECT Name, Potential_Revenue__c,  Client_Organization_Towers__c,
                                       Our_Revenue_Targets__c, Our_Business_Goals_Projects_we_want_to__c, 
                                       Key_Business_Priorities_of_Client__c, Major_Events__c,
                                       Client_IT_Landscape__c
                                       FROM Account_Plans__c WHERE Account_Name__c =: recordId];
        updatePlan.Account_Name__c = recordId; 
        updatePlan.Name = planName; 
        updatePlan.Potential_Revenue__c = revenue;
        updatePlan.Client_Organization_Towers__c = organizationTowers;
        updatePlan.Our_Revenue_Targets__c = revenueTargets;
        updatePlan.Our_Business_Goals_Projects_we_want_to__c = businessGoals;
        updatePlan.Key_Business_Priorities_of_Client__c = keyBusiness;
        updatePlan.Major_Events__c = events;
        updatePlan.Client_IT_Landscape__c = clientLandscape;
        update  updatePlan;
        return updatePlan;
    }   
}

//commit line 